packages:
  - "packages/*"
  - "apps/*"
overrides:
  postcss: 8.5.16
onlyBuiltDependencies:
  - esbuild
  - keccak
  - secp256k1
  - sharp
allowBuilds:
  esbuild: true
  keccak: true
  secp256k1: true
  sharp: true
